### ISSUE TITLE
Github download link not working

### ISSUE THREAD

**Issue by sslupsky** [Macschrauber/Macschrauber-s-Rom-Dump#1]
FYI, I tried the "Github Downloader to obtain a copy with no quarantine flag set" here:
https://github.com/Macschrauber/Macschrauber-s-Rom-Dump/blob/b943e781b48ee4ad3221c94dffb9025ee8e3bc57/README.md?plain=1#L108-L109

and I get a blank page with "Not Found" at the top.
![Screenshot 2024-04-02 at 9 49 08 AM](https://github.com/Macschrauber/Macschrauber-s-Rom-Dump/assets/16888734/e7b6ced1-0178-404c-a188-ea0f2057d0c2)

**Comment by Macschrauber** [comment]
Link is fixed, thanks for pointing me at it.

**Comment by DevX-Cipher** [comment]
@Macschrauber is there somewhere i can privately message you please

**Comment by Macschrauber** [comment]
yes, ***@***.***

**Comment by DevX-Cipher** [comment]
so another words no i can tell

**Comment by Macschrauber** [comment]
Github seems to block the email, lets try again in the web form:
macschrauber@gmx.de
