### ISSUE TITLE
Password to open dmg

### ISSUE THREAD

**Issue by Matgen84** [Macschrauber/Macschrauber-s-Rom-Dump#2]
Thanks for your great work.

I don't latest dmg file (5-08-2024): a password is required to open it !

Where I can find this password. Please.

**Comment by Macschrauber** [comment]
it's in the **readme.md**

https://github.com/Macschrauber/Macschrauber-s-Rom-Dump/blob/main/README.md


==> I needed to encrypt the disk image as Gatekeeper flaggs it for containing Flashrom. <==
The password is rom.

also the downloader automatically opens it: 
Use my Github Downloader to obtain a copy with no quarantine flag set:
https://github.com/Macschrauber/Macschrauber-s-Rom-Dump/releases/download/Release/Download.the.Dumper.from.github.zip
You may need to right-click on the App and select open.
