### ISSUE TITLE
Can this update firmware on mid 2010 5,1

### ISSUE THREAD

**Issue by mfat** [Macschrauber/Macschrauber-s-Rom-Dump#3]
Hi there
I have mid 2010 mmac pro which ran High Sierra. I've updated it to Big Sur using oclp but the bootrom version os still old.

**Comment by Macschrauber** [comment]
not directly, you need the 144.0.0.0.0 firmware with your machine's serials and IDs.

You can mail me your current dump and I can upgrade it.

Send it to Macschrauber#gmx.de - dont post it to a public board.
